In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
data=load_iris()

In [2]:
dir(data)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data.data,data.target,train_size=0.8)

In [4]:
from sklearn.model_selection import cross_val_score

In [9]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), data.data, data.target,cv=5)

array([1.        , 0.96666667, 0.93333333, 0.9       , 1.        ])

In [10]:
cross_val_score(LinearRegression(), data.data, data.target,cv=5)

array([0.        , 0.85124923, 0.        , 0.76155439, 0.        ])

In [11]:
cross_val_score(SVC(), data.data, data.target,cv=5)

c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarn

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [12]:
cross_val_score(DecisionTreeClassifier(), data.data, data.target,cv=5)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [15]:
cross_val_score(RandomForestClassifier(), data.data, data.target,cv=3)

c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array([0.98039216, 0.90196078, 0.97916667])