In [58]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
data=load_iris()

In [59]:
from sklearn.tree import DecisionTreeClassifier

In [60]:
dir(data)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [61]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data.data,data.target,train_size=0.8)

In [62]:
model_linear=LinearRegression()
model_linear.fit(x_train,y_train)
model_linear.score(x_test,y_test)

0.9443598993632707

In [63]:
model_tree=DecisionTreeClassifier()
model_tree.fit(x_train,y_train)
model_tree.score(x_test,y_test)

0.9333333333333333

In [64]:
model_svc=SVC()
model_svc.fit(x_train,y_train)
model_svc.score(x_test,y_test)

c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


1.0

In [65]:
model_RFC=RandomForestClassifier()
model_RFC.fit(x_train,y_train)
model_RFC.score(x_test,y_test)

c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.9666666666666667

In [66]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [67]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [73]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [69]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

from sklearn.linear_model import LogisticRegression


In [70]:
score_logi=[]
score_linear=[]
score_svm=[]
score_RF=[]
score_DT=[]

In [75]:
for train_index, test_index in folds.split(data.data,data.target):
    X_train, X_test, y_train, y_test = data.data[train_index], data.data[test_index], \
                                       data.target[train_index], data.target[test_index]

In [77]:
get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test)

0.9583333333333334