In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import pickle

In [2]:
df=pd.read_csv("canada.csv")
df.head(5)

year       income
0  1970  3399.299037
1  1971  3768.297935
2  1972  4251.175484
3  1973  4804.463248
4  1974  5576.514583

In [3]:
# %matplotlib inline
# plt.xlabel("year")
# plt.ylabel("per capita income(USD)")
# plt.scatter(df.year,df.income,marker='+')
# plt.plot(df.year,reg.predict(df[['year']]),color='red')

In [4]:
reg=linear_model.LinearRegression()
reg.fit(df[['year']],df.income)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
reg.predict([[2020]])

array([41288.69409442])

In [14]:
with open('model_pickle','wb') as file:
    pickle.dump(reg,file)

In [15]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [16]:
mp.predict([[2020]])

array([41288.69409442])

In [9]:
from sklearn.externals import joblib

c:\users\asus\appdata\local\programs\python\python37\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [11]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [12]:
mj=joblib.load('model_joblib')

In [13]:
mj.predict([[2020]])

array([41288.69409442])